<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="82000" started-at="2021-09-02T09:06:44Z" finished-at="2021-09-02T09:08:06Z">
    <groups>
    </groups>
    <test name="Regression" duration-ms="82000" started-at="2021-09-02T09:06:44Z" finished-at="2021-09-02T09:08:06Z">
      <class name="com.tabeo.automation.Tests.UnsuccessfulPaymentCardDeclinedTest">
        <test-method status="PASS" signature="LoginToApplication()[pri:0, instance:com.tabeo.automation.Tests.UnsuccessfulPaymentCardDeclinedTest@cb644e]" name="LoginToApplication" is-config="true" duration-ms="15845" started-at="2021-09-02T11:07:42Z" finished-at="2021-09-02T11:07:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginToApplication -->
        <test-method status="FAIL" signature="paymentDeclinedTestCase()[pri:0, instance:com.tabeo.automation.Tests.UnsuccessfulPaymentCardDeclinedTest@cb644e]" name="paymentDeclinedTestCase" duration-ms="6476" started-at="2021-09-02T11:07:58Z" finished-at="2021-09-02T11:08:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at com.tabeo.automation.Tests.UnsuccessfulPaymentCardDeclinedTest.paymentDeclinedTestCase(UnsuccessfulPaymentCardDeclinedTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- paymentDeclinedTestCase -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.tabeo.automation.Tests.UnsuccessfulPaymentCardDeclinedTest@cb644e]" name="closeBrowser" is-config="true" duration-ms="879" started-at="2021-09-02T11:08:05Z" finished-at="2021-09-02T11:08:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.tabeo.automation.Tests.UnsuccessfulPaymentCardDeclinedTest -->
      <class name="com.tabeo.automation.Tests.loginTestWithEmail">
        <test-method status="FAIL" signature="loginTestWithEmailAddress()[pri:0, instance:com.tabeo.automation.Tests.loginTestWithEmail@59494225]" name="loginTestWithEmailAddress" duration-ms="6560" started-at="2021-09-02T11:06:44Z" finished-at="2021-09-02T11:06:50Z">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[null value in entry: url=null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: null value in entry: url=null
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:32)
	at com.google.common.collect.SingletonImmutableBiMap.<init>(SingletonImmutableBiMap.java:42)
	at com.google.common.collect.ImmutableBiMap.of(ImmutableBiMap.java:72)
	at com.google.common.collect.ImmutableMap.of(ImmutableMap.java:124)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:277)
	at com.tabeo.automation.Tests.loginTestWithEmail.loginTestWithEmailAddress(loginTestWithEmail.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestWithEmailAddress -->
      </class> <!-- com.tabeo.automation.Tests.loginTestWithEmail -->
      <class name="com.tabeo.automation.Tests.LoginTestWithGmailOath">
        <test-method status="PASS" signature="LoginTestWithGmailAuthentication()[pri:0, instance:com.tabeo.automation.Tests.LoginTestWithGmailOath@6e1567f1]" name="LoginTestWithGmailAuthentication" duration-ms="18266" started-at="2021-09-02T11:06:50Z" finished-at="2021-09-02T11:07:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTestWithGmailAuthentication -->
        <test-method status="FAIL" signature="tearDown()[pri:0, instance:com.tabeo.automation.Tests.LoginTestWithGmailOath@6e1567f1]" name="tearDown" is-config="true" duration-ms="0" started-at="2021-09-02T11:08:06Z" finished-at="2021-09-02T11:08:06Z">
          <exception class="org.openqa.selenium.NoSuchSessionException">
            <message>
              <![CDATA[Session ID is null. Using WebDriver after calling quit()?
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'CHANDU', ip: '192.168.1.7', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_102'
Driver info: driver.version: RemoteWebDriver]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'CHANDU', ip: '192.168.1.7', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_102'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:125)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:609)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions.deleteAllCookies(RemoteWebDriver.java:694)
	at com.tabeo.automation.framework.core.Browser.tearDownTest(Browser.java:92)
	at com.tabeo.automation.Tests.LoginTestWithGmailOath.tearDown(LoginTestWithGmailOath.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:143)
	at org.testng.TestRunner.afterRun(TestRunner.java:973)
	at org.testng.TestRunner.run(TestRunner.java:604)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchSessionException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tabeo.automation.Tests.LoginTestWithGmailOath -->
      <class name="com.tabeo.automation.Tests.CreateSuccessfulPaymentTest">
        <test-method status="PASS" signature="LoginToApplication()[pri:0, instance:com.tabeo.automation.Tests.CreateSuccessfulPaymentTest@5cb9f472]" name="LoginToApplication" is-config="true" duration-ms="17012" started-at="2021-09-02T11:07:09Z" finished-at="2021-09-02T11:07:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginToApplication -->
        <test-method status="PASS" signature="successfulPaymentTestcase()[pri:0, instance:com.tabeo.automation.Tests.CreateSuccessfulPaymentTest@5cb9f472]" name="successfulPaymentTestcase" duration-ms="15197" started-at="2021-09-02T11:07:26Z" finished-at="2021-09-02T11:07:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- successfulPaymentTestcase -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.tabeo.automation.Tests.CreateSuccessfulPaymentTest@5cb9f472]" name="closeBrowser" is-config="true" duration-ms="1702" started-at="2021-09-02T11:07:41Z" finished-at="2021-09-02T11:07:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.tabeo.automation.Tests.CreateSuccessfulPaymentTest -->
    </test> <!-- Regression -->
  </suite> <!-- Suite -->
</testng-results>
